### ISSUE TITLE
Where are the target networks for KNN?

### ISSUE THREAD

**Issue by FinAminToastCrunch** [tumBAIS/dynamicNeighborhoodConstruction#2]
According to Dulac-Arnold, the wolpertinger is based on DDPG which is off-policy. I have not seen, in your implementation, the target network needed for KNN. Am I mistaking something or is there a reason why this was not done? I do not mean to sound accusatory, I am just wondering.

**Comment by frakkerman** [comment]
Thanks for your question!

As you correctly pointed out, Dulac-Arnold's Wolpertinger architecture is based on the DDPG algorithm, which typically employs off-policy learning and utilizes target networks. However, in our implementation, we've diverged somewhat from this approach. To facilitate a more direct and unambiguous comparison with other state-of-the-art methods (e.g., learning action representations) we employ a vanilla actor-critic framework (which does not employ target networks) and just embed the k-nearest neighbors (kNN) lookup into this framework, rather than adhering strictly to the Wolpertinger architecture as originally proposed. Hence, we intentionally moved away from the specialties of DDPG, including the use of target networks, to allow for a more pure focus on the comparison of different continuous-to-discrete mappings which is not biased by the underlying RL-algorithm.

**Comment by FinAminToastCrunch** [comment]
Thank you for your reply. The repository which you have made public has helped me tremendously in my dissertation research. Your commitment to reproducibility has saved me hundreds of hours. 

You can expect a citation of your work from me 🙂.

**Comment by frakkerman** [comment]
Thank you for your kind message! I'm really glad to hear the repository has been helpful for your dissertation and appreciate the citation.

**Comment by FinAminToastCrunch** [comment]
Entirely off-topic, I know that your paper does not address this at all, but I have a question. Do you know of any papers which deal with large discrete action spaces for recommendation systems? I know that you write that recommendation systems are not structured so they are outside the scope of your work. I was just curious.

**Comment by frakkerman** [comment]
You could give these papers a look, I believe all the proposed methods in these papers could be applied to such an environment: 

- https://arxiv.org/pdf/1512.07679.pdf 
- https://arxiv.org/abs/1906.01770
- https://arxiv.org/pdf/2011.01928.pdf

**Comment by FinAminToastCrunch** [comment]
Haha, I have read those 3 already! Glad Dr. Arnold and Chandak were of such help for you!

**Comment by FinAminToastCrunch** [comment]
Congrats on the ICLR acceptance!
